/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_RESIZER__
#define __RUST_RESIZER__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

void free_string (
    int8_t * str);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {

    uint8_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint8_t;

void free_buf (
    Vec_uint8_t vec);

Vec_uint8_t resize_image_with_percent (
    int8_t const * base64,
    uint32_t percent);

Vec_uint8_t resize_image_with_size (
    int8_t const * base64,
    uint32_t width,
    uint32_t height);

Vec_uint8_t resize_image (
    int8_t const * base64,
    uint32_t custom_width,
    uint32_t custom_height,
    uint32_t percent);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_RESIZER__ */
